# Generated by Django 5.1.2 on 2024-10-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Action",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Название действия"),
                ),
            ],
            options={
                "verbose_name": "Действие",
                "verbose_name_plural": "Действия",
            },
        ),
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_time", models.DateTimeField(verbose_name="Время выполнения")),
                (
                    "is_pleasant",
                    models.BooleanField(
                        default=False, verbose_name="Это приятная привычка"
                    ),
                ),
                (
                    "period",
                    models.CharField(
                        choices=[
                            ("DISABLE", "Отключено"),
                            ("EVERY_MINUTE", "Ежеминутно"),
                            ("EVERY_HOUR", "Ежечасно"),
                            ("EVERY_DAY", "Ежедневно"),
                            ("EVERY_WEEK", "Еженедельно"),
                        ],
                        default="DISABLE",
                        max_length=30,
                        verbose_name="периодичность",
                    ),
                ),
                (
                    "reward",
                    models.CharField(
                        default="", max_length=150, verbose_name="Вознаграждение"
                    ),
                ),
                (
                    "time_to_complete",
                    models.PositiveIntegerField(
                        default=120, verbose_name="Время на выполнение, c"
                    ),
                ),
                (
                    "is_public",
                    models.BooleanField(
                        default=False, verbose_name="Признак публичности"
                    ),
                ),
                (
                    "date_time_next_sent",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Дата и время следующего оповещения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Привычка",
                "verbose_name_plural": "Привычки",
            },
        ),
        migrations.CreateModel(
            name="Place",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=150, verbose_name="Название места"),
                ),
            ],
            options={
                "verbose_name": "Место",
                "verbose_name_plural": "Места",
            },
        ),
    ]
